# Generated by Django 2.1.7 on 2019-03-04 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crise', models.IntegerField(default=0)),
                ('date_response', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
